/**
 * Shape of the profile-wizard form state. Field names mirror the backend
 * Profile schema exactly (backend/src/models/Profile.js) so the payload can be
 * sent to PATCH /api/profiles/me without any remapping.
 */
export interface WizardFormData {
  fullName: string;
  // Step 1 — Personal Details
  dateOfBirth: string; // "YYYY-MM-DD"
  heightCm: number | "";
  maritalStatus: "never_married" | "divorced" | "widowed" | "awaiting_divorce" | "";
  manglik: "yes" | "no" | "dont_know";
  aboutMe: string;

  // Step 2 — Location
  district: string;
  // Only meaningful when district === "Other" — see Profile.js on the backend.
  customDistrict: string;
  tehsil: string;
  village: string;
  city: string;
  // Full residential address (house no., street, locality, pincode). Kept
  // as sensitive contact info on the backend — only ever shown to other
  // members once they unlock this profile's contact details.
  address: string;
  currentResidenceCountry: string;

  // Step 3 — Education & Career
  education: { degree: string; field: string; college: string };
  occupation: { title: string; company: string; annualIncomeRange: string };

  // Step 4 — Family Details
  family: {
    fatherOccupation: string;
    motherOccupation: string;
    siblings: number | "";
    familyType: "nuclear" | "joint" | "";
    familyValues: "traditional" | "moderate" | "liberal" | "";
  };

  // Step 5 — Religion & Horoscope
  religion: string;
  caste: string;
  subCaste: string;
  gotra: string;
  horoscope: { birthTime: string; birthPlace: string; rashi: string; nakshatra: string };

  // Step 6 — Lifestyle
  lifestyle: {
    diet: "vegetarian" | "non_vegetarian" | "eggetarian" | "vegan" | "";
    smoking: "no" | "occasionally" | "yes";
    drinking: "no" | "occasionally" | "yes";
  };
  interests: string[];

  // Step 7 — Partner Preference
  partnerPreference: {
    ageMin: number | "";
    ageMax: number | "";
    heightMinCm: number | "";
    districts: string[];
    education: string[];
    maritalStatus: string[];
  };

  // Step 8 & 9 — Photo handling attributes matching your backend Multer processing targets
  profileImage?: string; // Stored file path generated by server-side Multer (e.g. "uploads/profile-17199...jpg")
  avatarUrl?: string;    // Fully parsed endpoint route or CDN string absolute path
  photos?: ProfilePhoto[]; 

  // Visibility state
  visibility: "public" | "members_only" | "hidden";
}

export interface ProfilePhoto {
  url: string;
  publicId?: string;
  isProfilePhoto?: boolean;
  isPrivate?: boolean;
}

export const HP_DISTRICTS = [
  "Shimla", "Mandi", "Kullu", "Kangra", "Hamirpur", "Una",
  "Bilaspur", "Solan", "Sirmaur", "Chamba", "Kinnaur", "Lahaul-Spiti",
];

export const emptyWizardData: WizardFormData = {
  fullName: "",
  dateOfBirth: "",
  heightCm: "",
  maritalStatus: "",
  manglik: "dont_know",
  aboutMe: "",
  district: "",
  customDistrict: "",
  tehsil: "",
  village: "",
  city: "",
  address: "",
  currentResidenceCountry: "India",
  education: { degree: "", field: "", college: "" },
  occupation: { title: "", company: "", annualIncomeRange: "" },
  family: { fatherOccupation: "", motherOccupation: "", siblings: "", familyType: "", familyValues: "" },
  religion: "Hindu",
  caste: "",
  subCaste: "",
  gotra: "",
  horoscope: { birthTime: "", birthPlace: "", rashi: "", nakshatra: "" },
  lifestyle: { diet: "", smoking: "no", drinking: "no" },
  interests: [],
  partnerPreference: { ageMin: "", ageMax: "", heightMinCm: "", districts: [], education: [], maritalStatus: [] },
  profileImage: "",
  avatarUrl: "",
  photos: [],
  visibility: "members_only",
};
